# Generated by Django 6.0.4 on 2026-04-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_moneytransaction_user_expense_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('business', 'Business'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('projects', 'Projects'), ('hr', 'HR'), ('operations', 'Operations'), ('personal', 'Personal'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
