# Generated by Django 6.0.4 on 2026-04-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_note_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(blank=True, default='other', max_length=200),
        ),
    ]
