# Generated by Django 6.0.4 on 2026-04-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_note_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayplan',
            old_name='notes',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='dayplan',
            name='task',
        ),
        migrations.RemoveField(
            model_name='dayplan',
            name='title',
        ),
        migrations.AddField(
            model_name='dayplan',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
