# Generated by Django 6.0.4 on 2026-04-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_notes_dayplan_description_remove_dayplan_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
