# Generated by Django 6.0.4 on 2026-04-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_goal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(blank=True, default='not_started', max_length=100, null=True),
        ),
    ]
