# Generated by Django 6.0.4 on 2026-04-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_goal_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-income_date', '-id']},
        ),
        migrations.AddField(
            model_name='income',
            name='income_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
