# Generated by Django 6.0.4 on 2026-05-06 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_expense_options_alter_income_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=500)),
                ('result', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculator_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calculator History',
                'verbose_name_plural': 'Calculator Histories',
                'ordering': ['-id'],
            },
        ),
    ]
